services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8787:8787"
    volumes:
      - .:/myapp/      
    depends_on:
      - db
      - ribbit
    environment:
      - JWT_SECRET=PXEEFAjy9z9gMM23Pk4p
      - RABBIT_URI=amqp://rib:klsxx@ribbit:5672
    networks:
      - nest-network

  ribbit:
    image: rabbitmq:4-management
    ports:
      - '5672:5672'
      - '15672:15672'

    environment:
      RABBITMQ_DEFAULT_USER: rib
      RABBITMQ_DEFAULT_PASS: klsxx

    networks:
      - nest-network

  db:
    image: mongo:latest
    container_name: dbmongo
    ports:
      - "27017:27017"
    environment:
      MONGGO_INITDB_ROOT_USERNAME: root
      MONGGO_INITDB_ROOT_PASSWORD: klsxx
    volumes:
      - mongodb_data:/data/db
    networks:
      - nest-network

networks:
  nest-network: 

volumes:
  mongodb_data:

